server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  ai:
    openai:
      api-key: sk-430e069e0b8a4e4f828344764a4f1b7a
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: qwen3.7-plus
          temperature: 0.7
      #          maxTokens: 5000

      embedding:
        base-url: https://dashscope.aliyuncs.com/compatible-mode/
        api-key: sk-430e069e0b8a4e4f828344764a4f1b7a
        options:
          model: text-embedding-v4
          dimmension: 1024

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dodo?useUnicode=true&characterEncoding=UTF-8 # 记得改成你自己的
    username: root # 记得改成你自己的
    password: 123456 # 记得改成你自己的
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000

  # Redis 配置
  data:
    redis:
      host: 127.0.0.1  # 记得改成你自己的
      port: 6379
      database: 0
      timeout: 5s
      password: 123456

  # MyBatis-Plus 配置
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

minio:
  url: http://127.0.0.1:9001/   # 记得改成你自己的
  accessKey: minioadmin # 记得改成你自己的
  secretKey: minioadmin # 记得改成你自己的
  bucketName: dodo-agent
  endpoint: http://127.0.0.1:9001/

embeddings:
  store:
    host: 127.0.0.1   # 记得改成你自己的
    port: 5433   # 记得改成你自己的
    database: vector_store   # 记得改成你自己的
    user: pgvector   # 记得改成你自己的
    password: pgvector   # 记得改成你自己的

# Tavily 搜索引擎配置
tavily:
  api-key: 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  # 记得改成你自己的
  mcp-url: https://mcp.tavily.com/mcp/

grsai:
  nanobanana:
    api-key: sk-dfabc53adef24f3b93f9b8f1e0c270ea # 记得改成你自己的

logging:
  level:
    org:
      springframework:
        ai: INFO
    io:
      modelcontextprotocol:
        client: ERROR
skills:
  directory: C:\Users\Lenovo\.claude\skills  # 记得改成你自己的
