

server:
  port: 8001
spring:
  application:
    name: mcp-client
  ai:
    openai:
      api-key: sk-430e069e0b8a4e4f828344764a4f1b7a
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: qwen-max
          temperature: 0.7
          maxTokens: 5000
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 60s
        type: SYNC
        stdio:
          connections:
            weather-stdio:
              command: java
              args:
                - -jar
                - "/Users/ysl/Documents/IdeaProjects/llmentor/mcp/mcp-server-stdio/target/mcp-server-stdio-0.0.1-SNAPSHOT.jar"
        ##          servers-configuration: classpath:/mcp-servers.json
        sse:
          connections:
            weather-sse:
              url: http://127.0.0.1:8003/
              sse-endpoint: sse
        streamable-http:
          connections:
            weather-streamable:
              url: http://127.0.0.1:8004/stream/test/
              endpoint: api/mcp
