-- 车型信息表
create TABLE IF NOT EXISTS `car_info` (
    `id` BIGINT NOT NULL AUTO_INCREMENT comment '主键ID',
    `info_id` VARCHAR(64) NOT NULL comment '车型唯一标识',
    `brand` VARCHAR(64) DEFAULT NULL comment '品牌（如：Tesla、比亚迪、宝马等）',
    `model_name` VARCHAR(128) DEFAULT NULL comment '型号名称（如：Model 3、汉、3系等）',
    `model_year` INT DEFAULT NULL comment '年款（如：2025、2024等）',
    `version` VARCHAR(128) DEFAULT NULL comment '版本描述（如：焕新版、长续航版、运动版等）',
    `full_name` VARCHAR(256) DEFAULT NULL comment '全称（如：Tesla Model 3 2025焕新版）',
    `vehicle_type` VARCHAR(32) DEFAULT NULL comment '车辆类型：轿车/SUV/MPV/跑车/皮卡等',
    `fuel_type` VARCHAR(32) DEFAULT NULL comment '燃油类型：汽油/柴油/电动/混动/氢能源等',
    `seat_count` INT DEFAULT NULL comment '座位数',
    `displacement` DECIMAL(4,1) DEFAULT NULL comment '排量（L），燃油车使用',
    `motor_power` DECIMAL(8,2) DEFAULT NULL comment '电机功率（kW），电动车使用',
    `range_km` INT DEFAULT NULL comment '续航里程（km），电动车使用',
    `guide_price` DECIMAL(12,2) DEFAULT NULL comment '官方指导价（万元）',
    `color_options` VARCHAR(512) DEFAULT NULL comment '车身颜色选项（多个颜色用逗号分隔）',
    `dimensions` VARCHAR(64) DEFAULT NULL comment '车身尺寸（长x宽x高，单位mm）',
    `wheelbase` INT DEFAULT NULL comment '轴距（mm）',
    `manufacturer` VARCHAR(128) DEFAULT NULL comment '生产厂商',
    `status` VARCHAR(32) DEFAULT '在售' comment '车型状态：在售/停售/即将上市',
    `image_url` VARCHAR(512) DEFAULT NULL comment '车型图片URL',
    `description` TEXT DEFAULT NULL comment '车型描述',
    `remark` TEXT DEFAULT NULL comment '备注',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP comment '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON update CURRENT_TIMESTAMP comment '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_info_id` (`info_id`),
    KEY `idx_brand` (`brand`),
    KEY `idx_vehicle_type` (`vehicle_type`),
    KEY `idx_fuel_type` (`fuel_type`),
    KEY `idx_status` (`status`),
    KEY `idx_full_name` (`full_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci comment='车型信息表';


-- 我的车辆信息表
create TABLE IF NOT EXISTS `my_car` (
    `id` BIGINT NOT NULL AUTO_INCREMENT comment '主键ID',
    `car_id` VARCHAR(64) NOT NULL comment '车辆唯一标识',
    `user_id` VARCHAR(64) DEFAULT NULL comment '用户ID，标识车辆归属',
    `car_info_id` VARCHAR(64) DEFAULT NULL comment '关联的车型信息ID',
    `nickname` VARCHAR(128) DEFAULT NULL comment '车辆昵称（车主自定义名称）',
    `full_name` VARCHAR(256) DEFAULT NULL comment '车辆全称（如：Tesla Model 3 2025焕新版）',
    `image_url` VARCHAR(512) DEFAULT NULL comment '车辆图片URL',
    `order_id` VARCHAR(64) DEFAULT NULL comment '关联的购车订单ID',
    `plate_number` VARCHAR(32) NOT NULL comment '车牌号',
    `color` VARCHAR(32) DEFAULT NULL comment '车辆颜色（具体颜色，如：珍珠白、深海蓝等）',
    `vin` VARCHAR(32) DEFAULT NULL comment '车辆识别代号(VIN码)',
    `engine_number` VARCHAR(64) DEFAULT NULL comment '发动机号',
    `purchase_date` DATE DEFAULT NULL comment '购买日期',
    `purchase_price` DECIMAL(15,2) DEFAULT NULL comment '购买价格',
    `mileage` INT DEFAULT 0 comment '行驶里程(公里)',
    `register_date` DATE DEFAULT NULL comment '注册日期',
    `insurance_expire_date` DATE DEFAULT NULL comment '保险到期日',
    `inspection_expire_date` DATE DEFAULT NULL comment '年检到期日',
    `remark` TEXT DEFAULT NULL comment '备注',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP comment '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON update CURRENT_TIMESTAMP comment '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_car_id` (`car_id`),
    UNIQUE KEY `uk_plate_number` (`plate_number`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_car_info_id` (`car_info_id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci comment='我的车辆信息表';


-- 车辆订单表
create TABLE IF NOT EXISTS `car_order` (
    `id` BIGINT NOT NULL AUTO_INCREMENT comment '主键ID',
    `order_id` VARCHAR(64) NOT NULL comment '订单唯一标识',
    `user_id` VARCHAR(64) DEFAULT NULL comment '用户ID，标识订单归属',
    `car_id` VARCHAR(64) DEFAULT NULL comment '关联的车辆ID',
    `order_no` VARCHAR(64) NOT NULL comment '订单编号',
    `order_type` VARCHAR(32) DEFAULT NULL comment '订单类型：购买/出售/置换',
    `order_status` VARCHAR(32) DEFAULT '待支付' comment '订单状态：待支付/已支付/已完成/已取消',
    `brand` VARCHAR(64) DEFAULT NULL comment '车辆品牌',
    `model` VARCHAR(128) DEFAULT NULL comment '车辆型号',
    `color` VARCHAR(32) DEFAULT NULL comment '车辆颜色',
    `vin` VARCHAR(32) DEFAULT NULL comment '车辆VIN码',
    `seller_name` VARCHAR(256) DEFAULT NULL comment '卖家/经销商名称',
    `seller_contact` VARCHAR(128) DEFAULT NULL comment '卖家/经销商联系方式',
    `vehicle_price` DECIMAL(15,2) DEFAULT NULL comment '车辆价格',
    `purchase_tax` DECIMAL(15,2) DEFAULT NULL comment '购置税',
    `insurance_fee` DECIMAL(15,2) DEFAULT NULL comment '保险费用',
    `other_fee` DECIMAL(15,2) DEFAULT NULL comment '其他费用',
    `total_amount` DECIMAL(15,2) DEFAULT NULL comment '订单总金额',
    `discount_amount` DECIMAL(15,2) DEFAULT NULL comment '优惠金额',
    `actual_amount` DECIMAL(15,2) DEFAULT NULL comment '实际支付金额',
    `payment_method` VARCHAR(32) DEFAULT NULL comment '付款方式：全款/分期',
    `order_date` DATE DEFAULT NULL comment '订单日期',
    `delivery_date` DATE DEFAULT NULL comment '交付日期',
    `remark` TEXT DEFAULT NULL comment '备注',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP comment '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON update CURRENT_TIMESTAMP comment '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_id` (`order_id`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_car_id` (`car_id`),
    KEY `idx_order_status` (`order_status`),
    KEY `idx_order_type` (`order_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci comment='车辆订单表';