spring:
  application:
    name: llmentor

  ai:
    dashscope:
      api-key: sk-430e069e0b8a4e4f828344764a4f1b7a

    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3:latest

    chat:
      memory:
        repository:
          jdbc:
            platform: mysql
            initialize-schema: always

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_ai_db2?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

dashscope:
  api-key: ${DASHSCOPE_API_KEY:}
  api-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
  model: qwen-plus
