spring:
  application:
    name: llmentor

  ai:
    dashscope:
      api-key: sk-430e069e0b8a4e4f828344764a4f1b7a

server:
  port: 8080

dashscope:
  api-key: ${DASHSCOPE_API_KEY:}
  api-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
  model: qwen-plus
