server:
  port: 8009

spring:
  application:
    name: KnowEngine
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/know_engine?rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid:
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      login-username: admin
      login-password: admin
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j666
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      ssl:
        enabled: true
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: 123456
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://localhost:6379"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

langchain4j:
  open-ai:
    chat-model:
      api-key: @dashscope.api.key@
      model-name: qwen3-30b-a3b-instruct-2507
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
    streaming-chat-model:
      api-key: @dashscope.api.key@
      model-name: qwen3-30b-a3b-instruct-2507
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      log-requests: true
      log-responses: true
  community:
    neo4j:
      enabled: false
      await-index-timeout: 300
      auth:
        uri: bolt://localhost:7687
        user: neo4j
        password: neo4j666

elasticsearch:
  host: http://127.0.0.1:9200
  base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model-name: text-embedding-v4
  api-key: @dashscope.api.key@
  dimensions: 1536

minio:
  url: http://localhost:9000 # 记得改成你自己的
  accessKey: minioadmin # 记得改成你自己的
  secretKey: minioadmin # 记得改成你自己的
  bucketName: know-engine # 记得改成你自己的
  endpoint: http://localhost:9000 # 记得改成你自己的

# 图数据库
neo4j:
  uri: bolt://localhost:7687
  username: neo4j
  password: neo4j666

# 文件解析服务配置
file:
  parse:
    api:
      url: http://47.104.64.223:8000 # 文档解析接口地址，记得改成你自己的

# XXL-Job 配置
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin # xxl-job-admin 地址，记得改成你自己的
    accessToken: default_token
    executor:
      appname: know-engine-executor # 执行器名称

dingtalk:
  #  配置项目启动不依赖钉钉
  enabled: false
  appKey: dingvvfhrqrpk6fbifdz
  appSecret: MUgUPvInkA3w2fOTu7hdfRuRV8Q3kGG3pWk_oremx-OYoUZ9TJT5JsAULx_QYPGS
  robotCode: dingvvfhrqrpk6fbifdz

# Sa-Token 配置
sa-token:
  # token 名称（同时也是 Cookie 名称、Header 名称）
  token-name: satoken
  # token 有效期（秒），默认 30 天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（秒），如果 token 超过这个时间没有访问系统就会被冻结，默认-1 代表不限制
  active-timeout: -1
  # 是否允许同一账号并发登录（为 true 时允许一起登录，为 false 时新登录会挤下旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token（为 true 时所有登录共用一个 token，为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（uuid）
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从 cookie 中读取 token
  is-read-cookie: true
  # 是否从 header 中读取 token
  is-read-header: true
